### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fatifan** [Farbod-Parsa/WARP-PLUS#1]
Not working :(

**Comment by Farbod-Parsa** [comment]
Hi FatiFan,

Thank you for bringing this to my attention. I sincerely apologize for any inconvenience caused by the error. The code has been updated just moments ago.

If possible, please review the following details:

Enter the correct ID from the following guide (select "Advanced," then "Diagnostics," and locate the ID key).
Ensure that you have installed the latest version of the app.
Feel free to reach out if you have any questions or if there's anything else you'd like to add.

Thank you,
Farbod Parsa

**Comment by Fatifan** [comment]
![Screenshot_20240109-051500_Chrome](https://github.com/Farbod-Parsa/WARP-PLUS/assets/125193909/b4926790-81ed-46cf-afff-390d542108bf)

**Comment by Farbod-Parsa** [comment]
Hello again, Fatifan. 
Thank you for sending the error photo. I've examined the code, and my terminal doesn't indicate any server errors. However, I will review all the code lines again and reply shortly.

**Comment by Farbod-Parsa** [comment]
![Undfffghgtitled](https://github.com/Farbod-Parsa/WARP-PLUS/assets/153591961/22643b8a-aebf-460b-960c-b210df01c4a0)

**Comment by Fatifan** [comment]
Thanks 
I entered key instead of id by mistake. The problem is now solved
